version: "3.8"

services:
  ems-backend:
    build: .
    container_name: ems-backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      stdin_open: true
      tty: true
      command: npm start